[tool.black]
extend-exclude = '''
  /rebench/interop/jmh_adapter.py
| /rebench/interop/savina_log_adapter.py
| /rebench/interop/perf_adapter.py
| /rebench/interop/adapter.py
| /rebench/interop/test_adapter.py
| /rebench/interop/test_vm_adapter.py
| /rebench/environment.py
| /rebench/interop/plain_seconds_log_adapter.py
| /rebench/interop/multivariate_adapter.py
| /rebench/model/build_cmd.py
| /rebench/interop/validation_log_adapter.py
| /rebench/interop/rebench_log_adapter.py
| /rebench/model/benchmark.py
| /rebench/denoise_client.py
| /rebench/model/benchmark_suite.py
| /rebench/model/executor.py
| /rebench/model/exp_run_details.py
| /rebench/model/profile_data.py
| /rebench/interop/time_adapter.py
| /rebench/model/profiler.py
| /rebench/model/reporting.py
| /rebench/output.py
| /rebench/interop/perf_parser.py
| /rebench/model/data_point.py
| /rebench/model/measurement.py
| /rebench/model/experiment.py
| /rebench/configurator.py
| /rebench/subprocess_kill.py
| /rebench/denoise.py
| /rebench/model/termination_check.py
| /rebench/tests/bugs/issue_27_invalid_run_not_handled_test.py
| /rebench/tests/bugs/issue_112_invocations_setting_ignored_test.py
| /rebench/statistics.py
| /rebench/tests/bugs/issue_54_extra_args_test.py
| /rebench/tests/bugs/issue_117_input_size_setting_ignored_test.py
| /rebench/rebenchdb.py
| /rebench/tests/bugs/issue_111_report_ignores_warmup_test.py
| /rebench/tests/bugs/issue_4_run_equality_and_params_test.py
| /rebench/tests/environment_test.py
| /rebench/tests/features/issue_15_warm_up_support_test.py
| /rebench/tests/features/ignore_timeouts_test.py
| /rebench/model/run_id.py
| /rebench/subprocess_with_timeout.py
| /rebench/tests/features/issue_169_config_composition_test.py
| /rebench/tests/features/issue_16_multiple_data_points_test.py
| /rebench/tests/features/issue_209_adapter.py
| /rebench/tests/features/issue_110_setup_run_test.py
| /rebench/tests/configurator_test.py
| /rebench/tests/features/issue_19_one_data_point_test.py
| /rebench/tests/features/issue_216_test.py
| /rebench/tests/features/issue_32_jmh_support_test.py
| /rebench/tests/executor_test.py
| /rebench/tests/features/issue_209_adapter2.py
| /rebench/tests/features/issue_42_vm.py
| /rebench/tests/features/issue_57_binary_on_path_test.py
| /rebench/reporter.py
| /rebench/tests/features/issue_34_accept_faulty_runs_test.py
| /rebench/tests/features/issue_209_custom_adapter_test.py
| /rebench/tests/interop/plain_seconds_log_adapter_test.py
| /rebench/tests/features/issue_31_multivariate_data_points_test.py
| /rebench/tests/interop/time_adapter_test.py
| /rebench/tests/features/issue_59_build_suite_test.py
| /rebench/tests/features/issue_81_unicode_test.py
| /rebench/tests/features/issue_58_build_vm_test.py
| /rebench/tests/mock_http_server.py
| /rebench/persistence.py
| /rebench/tests/rebenchdb_test.py
| /rebench/tests/rebench_test_case.py
| /rebench/executor.py
| /rebench/tests/model/runs_config_test.py
| /setup.py
| /rebench/tests/subprocess_timeout_test.py
| /rebench/tests/stats_test.py
| /rebench/tests/reporter_test.py
| /rebench/tests/features/issue_42_test.py
| /rebench/rebench.py
| /rebench/tests/interop/rebench_log_adapter_test.py
| /rebench/tests/perf/perf_parser_test.py
| /rebench/tests/perf/issue_166_profiling_test.py
| /rebench/ui.py
| /rebench/tests/persistency_test.py
'''
